alias cli='ncs_cli -u admin'
alias ncs_reset='make -C $CONFDX_DIR/lib/webui/webui-one/ncs reset'
alias tailf='cd ~/dev/git/tailf/'
alias one="cd ${NCS_DIR}/../lib/webui/webui-one"

# alias vim='exec_scmb_expand_args /usr/bin/vim'
alias vim='~/dev/git/dotfiles/nvim.appimage'
alias nvim='~/dev/git/dotfiles/nvim.appimage'
alias vi='vim'
alias dot='cd ~/dev/git/dotfiles'
alias la='ls -la'
alias pycli='ipython ~/dev/git/ncs_pycli/ncs_pycli'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias rbashrc='. ~/.bashrc'
alias bashal='vim ~/.bash_aliases'
alias ,yb='git rev-parse --abbrev-ref HEAD | xargs echo -n | xclip -selection c'

alias gfoc='git-fzf-checkout.sh'
if [[ $- =~ i ]]; then
  # bind '"\er": redraw-current-line'
  # bind '"\C-g\C-f": "$(_gf)\e\C-e\er"'
  bind -x '"\C-g\C-b": "git-fzf-branches.sh"'
  bind '"\C-g\C-c": "git-fzf-checkout.sh\n"'
  # bind '"\C-g\C-t": "$(_gt)\e\C-e\er"'
  # bind '"\C-g\C-h": "$(_gh)\e\C-e\er"'
  # bind '"\C-g\C-r": "$(_gr)\e\C-e\er"'
  # bind '"\C-g\C-s": "$(_gs)\e\C-e\er"'
fi

# alias gd='git diff --color | diff-so-fancy'
alias ciscovpn='openconnect-sso -s https://ams-vpn-cluster.cisco.com/ssl'
alias ciscovpn1='openconnect-sso -s https://aer01-hda1-vpn-cluster-1.cisco.com/ssl'
alias ciscovpn2='openconnect-sso -s https://aer02-hda1-vpn-cluster-2.cisco.com/ssl'
alias ciscovpn3='openconnect-sso -s https://aer01-hda1-vpn-cluster-3.cisco.com/ssl'
alias ciscovpn4='openconnect-sso -s https://aer02-hda1-vpn-cluster-4.cisco.com/ssl'
alias ciscovpn5='openconnect-sso -s https://aer01-hda1-vpn-cluster-5.cisco.com/ssl'
